// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUoZg_inxdzxjq92pAxnMqv_Bxg7y9ZLg',
    appId: '1:990403894763:web:d1bac8099843305842cdae',
    messagingSenderId: '990403894763',
    projectId: 'flip-7d204',
    authDomain: 'flip-7d204.firebaseapp.com',
    storageBucket: 'flip-7d204.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPjpk3WtVr4tyzO5E-VliLEoVf084LlZQ',
    appId: '1:990403894763:android:0f398b53844b874c42cdae',
    messagingSenderId: '990403894763',
    projectId: 'flip-7d204',
    storageBucket: 'flip-7d204.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdPZINyS4MpV_oMolFCpYYU4g92t9KVkM',
    appId: '1:990403894763:ios:150d84cba157133642cdae',
    messagingSenderId: '990403894763',
    projectId: 'flip-7d204',
    storageBucket: 'flip-7d204.appspot.com',
    iosBundleId: 'com.example.flip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdPZINyS4MpV_oMolFCpYYU4g92t9KVkM',
    appId: '1:990403894763:ios:7a1856cf247f435442cdae',
    messagingSenderId: '990403894763',
    projectId: 'flip-7d204',
    storageBucket: 'flip-7d204.appspot.com',
    iosBundleId: 'com.example.flip.RunnerTests',
  );
}
